### ISSUE TITLE
不知道为啥就出现编码问题

### ISSUE THREAD

**Issue by ZZtac** [yhy0/SScan#5]
Traceback (most recent call last):
  File "D:\webscan\SScan-0.5\SScan.py", line 322, in <module>
    fire.Fire(SScan)
  File "D:\python\python3\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\python\python3\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\python\python3\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "D:\webscan\SScan-0.5\SScan.py", line 304, in run
    self.print()
  File "D:\webscan\SScan-0.5\SScan.py", line 295, in print
    self.config_param()
  File "D:\webscan\SScan-0.5\SScan.py", line 123, in config_param
    content = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 124: illegal multibyte sequence

**Comment by yhy0** [comment]
自己有没有添加脚本，如果添加了是不是有什么特殊字符之类的，可以尝试修改 SScan.py  122行 
`  with open(_script, encoding='UTF-8') as f: ` 为 ` with open(_script, encoding='UTF-8', errors='ignore') as f:`  
忽略非法字符
