### ISSUE TITLE
总是报错Unhandled exception in event loop

### ISSUE THREAD

**Issue by ccstuck** [yhy0/SScan#6]
Mac环境，不知道为啥每次运行一阵子报错，装环境的时候都正常。
Unhandled exception in event loop
Traceback (most recent call last):
  File "uvloop/dns.pyx", line 389, in uvloop.loop.__on_addrinfo_resolved
  File "uvloop/loop.pyx", line 926, in uvloop.loop.Loop._getaddrinfo.callback
  File "uvloop/loop.pyx", line 1276, in  #uvloop.loop.Loop.call_soon
  File "uvloop/loop.pyx", line 667, in uvloop.loop.Loop._call_soon
  File "uvloop/loop.pyx", line 671, in uvloop.loop.Loop._call_soon_handle
  File "uvloop/loop.pyx", line 700, in uvloop.loop.Loop._check_closed

**Comment by yhy0** [comment]
这个错误我查了一下，可能是python的问题(不过应该是大概率我写的有点问题)，新的版本这几天会发布，我优化了一下前期的模块，发布后你再试试
